blank_issues_enabled: true
contact_links:
  - about: Ask and answer questions about the NeuralCompression package
    name: NeuralCompression Issues
    url: https://github.com/facebookresearch/NeuralCompression/issues
