jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - run: tox -e ${{ matrix.task }}
    strategy:
      matrix:
        task: [ black, flake8, import-lint, isort]
name: test
on:
  pull_request:
    branches:
      - main
