_target_: improved_diffusion.script_util.create_model
image_size: ${data.val.image_size}
num_channels: 128
num_res_blocks: 3
learn_sigma: ${diffusion.learn_sigma}
class_cond: false
use_checkpoint: false
attention_resolutions: 16,8
num_heads: 4
num_heads_upsample: -1
use_scale_shift_norm: true
dropout: 0.0
